### ISSUE TITLE
warn: [MungeDetector] Failed

### ISSUE THREAD

**Issue by papuas** [breeswish/ingress-exporter#22]
hi,  i got these errors while runnig the script:

2015-02-02T11:37:50.646Z - info: [MungeDetector] Trying to use internal munge data.
2015-02-02T11:37:51.179Z - warn: [MungeDetector] Failed.
2015-02-02T11:37:51.180Z - info: [MungeDetector] Trying to extract munge data from ingress.com/intel.
[Error: Failed to extract version]
2015-02-02T11:37:51.687Z - warn: [MungeDetector] Failed.
2015-02-02T11:37:51.688Z - error: [MungeDetector] Could not detect munge data. Tasks are terminated.

Any ideas?

**Comment by danizwam** [comment]
Niantic changed the MungeData. IITC fixed this two days ago.

I think this are the changes: https://github.com/jonatkins/ingress-intel-total-conversion/commit/ae89885c41714e76dd8233da4e6a2583e27733e3

I looked into the code but i have no idea what to do :(
Maybe @mrcerf can help?

**Comment by mrcerf** [comment]
if only i knew js better...
i am very not sure, but seems they have put "version" into request function, thus simply getting it will requires some js knowledge :)
so i went other way... just regex it out of source :D

```
diff --git a/src/lib/utils.js b/src/lib/utils.js
index 050529a..1d3bb71 100644
--- a/src/lib/utils.js
+++ b/src/lib/utils.js
@@ -34,12 +34,16 @@ var Utils = GLOBAL.Utils = {
         // execute JavaScript
         eval(source);
         Utils.extractFromStock(window);
+        
+        r=/.*c\.v="([^"]*)".*/; 
+        CURRENT_VERSION=r.exec(source)[1];
+        console.log(CURRENT_VERSION);
 
-        if (window.niantic_params.CURRENT_VERSION == undefined) {
+        if (CURRENT_VERSION == undefined) {
             throw new Error('Failed to extract version');
         }
 
-        return window.niantic_params;
+        return {CURRENT_VERSION:CURRENT_VERSION};
     },
 
     // from IITC code
```

**Comment by mrcerf** [comment]
just pull

**Comment by danizwam** [comment]
@mrcerf thx ;)

**Comment by papuas** [comment]
@mrcerf tnx ))))
